In [1]:
import pandas as pd

In [11]:
adroit_file = "data/balanced_adroit.csv"
adroit = pd.read_csv(adroit_file)
print(f"Arquivo carregado: {adroit_file}")
adroit.head()

Arquivo carregado: data/balanced_adroit.csv

,android.permission.BIND_WALLPAPER,android.permission.READ_CALENDAR,android.permission.READ_SYNC_STATS,android.permission.INTERNET,android.permission.CHANGE_CONFIGURATION,com.android.browser.permission.WRITE_HISTORY_BOOKMARKS,com.android.launcher.permission.INSTALL_SHORTCUT,android.permission.WRITE_CALL_LOG,android.permission.CHANGE_WIFI_MULTICAST_STATE,android.permission.SET_TIME_ZONE,...,android.permission.CLEAR_APP_CACHE,android.permission.CAPTURE_VIDEO_OUTPUT,android.permission.GET_TOP_ACTIVITY_INFO,android.permission.READ_SMS,android.permission.BATTERY_STATS,android.permission.PACKAGE_USAGE_STATS,android.permission.ACCESS_DRM,android.permission.BROADCAST_STICKY,android.permission.MOUNT_UNMOUNT_FILESYSTEMS,class
0,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
adrocrawl_file = "data/balanced_androcrawl.csv"
adrocrawl = pd.read_csv(adrocrawl_file)
print(f"Arquivo carregado: {adrocrawl_file}")
adrocrawl.head()

Arquivo carregado: data/balanced_androcrawl.csv

,Dangerous Permission: ACCESS_SUPERUSER,Dangerous Permission: CHANGE_COMPONENT_ENABLED_STATE,Dangerous Permission: CLEAR_APP_USER_DATA,Dangerous Permission: DELETE_CACHE_FILES,Dangerous Permission: DELETE_PACKAGES,Dangerous Permission: DISABLE_KEYGUARD,Dangerous Permission: FACTORY_TEST,Dangerous Permission: INSTALL_PACKAGES,Dangerous Permission: INJECT_EVENTS,Dangerous Permission: INTERNAL_SYSTEM_WINDOW,...,Suspicious Intent Filter: USER_PRESENT,Hidden Apk,Sends SMS to Suspicious Number(s),Package Domain Exists,Reads phone data at startup,Sends SMS at startup,Starts service at startup,Sends SMS when receiving SMS,Accesses a database when receiving SMS,class
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

In [15]:
adrocrawl.columns

Index(['Dangerous Permission: ACCESS_SUPERUSER',
       'Dangerous Permission: CHANGE_COMPONENT_ENABLED_STATE',
       'Dangerous Permission: CLEAR_APP_USER_DATA',
       'Dangerous Permission: DELETE_CACHE_FILES',
       'Dangerous Permission: DELETE_PACKAGES',
       'Dangerous Permission: DISABLE_KEYGUARD',
       'Dangerous Permission: FACTORY_TEST',
       'Dangerous Permission: INSTALL_PACKAGES',
       'Dangerous Permission: INJECT_EVENTS',
       'Dangerous Permission: INTERNAL_SYSTEM_WINDOW',
       ...
       'Suspicious Intent Filter: USER_PRESENT', 'Hidden Apk',
       'Sends SMS to Suspicious Number(s)', 'Package Domain Exists',
       'Reads phone data at startup', 'Sends SMS at startup',
       'Starts service at startup', 'Sends SMS when receiving SMS',
       'Accesses a database when receiving SMS', 'class'],
      dtype='str', length=137)